# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cbc2dcc281c3419db56312156753dfa4a871a5fd5ada70aa193e37d5cd4b82deeed13ce9f9f06d1b442efa33ba843e1a883689255be16ecb68511cbe973e03

test:
  secret_key_base: f81a96b99dec03a92251451a49fd7ab2c085c92b68e6dbfbbabbac75dc6e7143ff936e0f156ac0c48215761ded81ef7f731aa95be9daeb9e3c7ad04893284b20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
